name: Unit Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths:
    - 'builddefs/**'
    - 'quantum/**'
    - 'platforms/**'
    - 'tmk_core/**'
    - 'tests/**'
    - '*.mk'
    - 'Makefile'
    - '.github/workflows/unit_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run tests
      run: make test:all
